# Generated by Django 5.2.6 on 2025-09-06 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('agent_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('system_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, help_text='Chapter context for this chat session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.chapter')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject context for this chat session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('ASSISTANT', 'Assistant Response'), ('SYSTEM', 'System Message'), ('ERROR', 'Error Message')], max_length=20)),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True, help_text='Rendered HTML content')),
                ('token_count', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('context_used', models.JSONField(blank=True, default=list, help_text='Retrieved context chunks')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Source documents')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CHAT_QUERY', 'Chat Query'), ('DOCUMENT_SEARCH', 'Document Search'), ('EMBEDDING_GENERATION', 'Embedding Generation'), ('SUMMARIZATION', 'Text Summarization')], default='CHAT_QUERY', max_length=50)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('cost_input', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_output', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('model_used', models.CharField(max_length=100)),
                ('documents_retrieved', models.IntegerField(default=0)),
                ('chunks_used', models.IntegerField(default=0)),
                ('retrieval_time', models.FloatField(default=0, help_text='Retrieval time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='chat.message')),
            ],
            options={
                'db_table': 'chat_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Memory key/identifier', max_length=200)),
                ('value', models.TextField(help_text='Memory content')),
                ('context', models.TextField(blank=True, help_text='Additional context')),
                ('memory_type', models.CharField(choices=[('PREFERENCE', 'User Preference'), ('FACT', 'User Fact'), ('GOAL', 'User Goal'), ('CONTEXT', 'Context Information'), ('LEARNING', 'Learning Progress')], default='FACT', max_length=50)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1')),
                ('importance', models.IntegerField(default=5, help_text='Importance score 1-10')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memories', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='chat.message')),
            ],
            options={
                'db_table': 'conversation_memories',
                'ordering': ['-importance', '-updated_at'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
